export { PROTOCOL_VERSION, CAPABILITY_FLAGS, STRICT_AGENT_ONLY_CAPABILITY } from './version';
export type { CapabilityFlag } from './version';

export { BlobRefSchema, CONTENT_HASH_RE } from './blob';
export type { BlobRef } from './blob';

export { PermissionPolicySchema, PERMISSION_MODES } from './permission';
export type { PermissionPolicy, PermissionMode } from './permission';

export {
  AgentEventSchema,
  UnknownAgentEventSchema,
  AgentEventOrUnknownSchema,
  KNOWN_AGENT_EVENT_TYPES,
  isKnownAgentEvent,
  partitionAgentEvents,
} from './agent-event';
export type { AgentEvent, UnknownAgentEvent, AgentEventOrUnknown } from './agent-event';

export {
  AgentEgressPolicySchema,
  AgentEgressActivityPolicySchema,
  AgentReliableQuotaPolicySchema,
  ContentReadPolicySchema,
  AgentEgressLaneSchema,
  AgentEgressDropReasonSchema,
  AgentContentReadSurfaceSchema,
  AgentContentActorKindSchema,
  AgentContentActorSchema,
  AgentContentDecodeAsSchema,
  AgentContentMimeTypeSchema,
  AgentContentReadDecisionSchema,
  AgentContentReadDenialReasonSchema,
  AgentEgressContentHashSchema,
  AgentEgressPolicyRevisionSchema,
  AgentMessageContractSchema,
  AgentMessageContentTypeSchema,
  AgentMessageDestinationBindingSchema,
  AgentMessageFreshnessCursorSchema,
  AgentMessageServerContextSchema,
  AgentMessageEgressRequirementSchema,
  AGENT_MESSAGE_MAX_BYTES,
  AGENT_MESSAGE_EGRESS_CAPABILITY,
  AGENT_EGRESS_POLICY_CAPABILITY,
  AGENT_EGRESS_RELIABLE_ACK_CAPABILITY,
  AGENT_EGRESS_FRESH_SESSION_CAPABILITY,
  AGENT_CONTENT_WORKSPACE_READ_CAPABILITY,
  AGENT_CONTENT_TRANSCRIPT_READ_CAPABILITY,
  AGENT_CONTENT_ARTIFACT_READ_CAPABILITY,
} from './agent-egress';
export type {
  AgentEgressPolicy,
  AgentEgressActivityPolicy,
  AgentReliableQuotaPolicy,
  ContentReadPolicy,
  AgentEgressLane,
  AgentEgressDropReason,
  AgentMessageContentType,
  AgentMessageEgressRequirement,
  AgentMessageServerContext,
  AgentContentReadSurface,
  AgentContentActorKind,
  AgentContentActor,
  AgentContentDecodeAs,
  AgentContentReadDecision,
  AgentContentReadDenialReason,
} from './agent-egress';

export {
  AGENT_HOME_PROJECTION_CAPABILITY,
  AGENT_HOME_PROJECTION_MAX_BYTES,
  AGENT_HOME_PROJECTION_PROFILE_REVISION_MAXIMUM,
  AgentHomeProjectionProfileRevisionSchema,
  AgentHomeProjectionHashSchema,
  AgentHomeProjectionOutcomeSchema,
  AgentHomeProjectionValueSchema,
} from './agent-home-projection';
export type {
  AgentHomeProjectionProfileRevision,
  AgentHomeProjectionHash,
  AgentHomeProjectionOutcome,
  AgentHomeProjectionValue,
} from './agent-home-projection';

export {
  TERMINAL_PROJECTION_SELECTION_CAPABILITY,
  TerminalProjectionContractSchema,
  TerminalProjectionSelectionSchema,
} from './terminal-projection';
export type { TerminalProjectionSelection } from './terminal-projection';

export { TASK_STATES, TASK_TRANSITIONS, canTransition } from './task-state';
export type { TaskState } from './task-state';

export {
  MESSAGE_TYPES,
  MESSAGE_PAYLOAD_SCHEMAS,
  SERVER_TO_DAEMON_TYPES,
  DAEMON_TO_SERVER_TYPES,
  RuntimeIdSchema,
  ProtocolVersionNumberSchema,
  RuntimeInfoSchema,
  RuntimeCapabilitiesSchema,
  AgentRefSchema,
  AgentHomeProjectionAgentRefSchema,
  AGENT_REF_MAX_BYTES,
  DispatchSelectionSchema,
  ToolsetIdSchema,
  ConfiguredToolsetsSchema,
  RequiredToolsetsSchema,
  CONFIGURED_TOOLSETS_MAX_ITEMS,
  ConnHelloPayloadSchema,
  ConnAckPayloadSchema,
  TaskOfferPayloadSchema,
  TaskOfferWithToolsetsPayloadSchema,
  TaskOfferForAgentPayloadSchema,
  TaskOfferForAgentWithEgressPayloadSchema,
  TaskOfferForAgentWithEgressFreshPayloadSchema,
  AgentEgressReliablePayloadSchema,
  AgentEgressAckPayloadSchema,
  AgentMessagePublishPayloadSchema,
  AgentMessageDispositionPayloadSchema,
  AgentContentReadPayloadSchema,
  AgentContentReceiptPayloadSchema,
  AgentHomeProjectionPayloadSchema,
  TaskApprovePayloadSchema,
  TaskRejectPayloadSchema,
  TaskCancelPayloadSchema,
  TaskSteerPayloadSchema,
  TaskClaimPayloadSchema,
  TaskStartedPayloadSchema,
  TaskDeclinePayloadSchema,
  TaskProgressPayloadSchema,
  TaskArtifactPayloadSchema,
  TaskAwaitApprovalPayloadSchema,
  TaskCompletePayloadSchema,
  TaskFailPayloadSchema,
  TaskCancelledPayloadSchema,
  TaskApprovalResolvedPayloadSchema,
  RESULT_DOCUMENT_MAX_BYTES,
  checkResultDocument,
  TerminalInferenceUsageSchema,
  TERMINAL_INFERENCE_USAGE_MAX_TOKENS,
  TERMINAL_INFERENCE_USAGE_MAX_DURATION_MS,
  TERMINAL_INFERENCE_USAGE_PROVIDER_MAX_LENGTH,
  TERMINAL_INFERENCE_USAGE_MODEL_MAX_LENGTH,
  TERMINAL_INFERENCE_USAGE_CLIENT_VERSION_MAX_LENGTH,
} from './messages';
export type {
  ResultDocumentCheck,
  MessageType,
  RuntimeId,
  RuntimeInfo,
  RuntimeCapabilities,
  AgentRef,
  AgentHomeProjectionAgentRef,
  DispatchSelection,
  ToolsetId,
  ConnHelloPayload,
  ConnAckPayload,
  TaskOfferPayload,
  TaskOfferWithToolsetsPayload,
  TaskOfferForAgentPayload,
  TaskOfferForAgentWithEgressPayload,
  TaskOfferForAgentWithEgressFreshPayload,
  AgentEgressReliablePayload,
  AgentEgressAckPayload,
  AgentMessagePublishPayload,
  AgentMessageDispositionPayload,
  AgentContentReadPayload,
  AgentContentReceiptPayload,
  AgentHomeProjectionPayload,
  TaskApprovePayload,
  TaskRejectPayload,
  TaskCancelPayload,
  TaskSteerPayload,
  TaskClaimPayload,
  TaskStartedPayload,
  TaskDeclinePayload,
  TaskProgressPayload,
  TaskArtifactPayload,
  TaskAwaitApprovalPayload,
  TaskCompletePayload,
  TaskFailPayload,
  TaskCancelledPayload,
  TaskApprovalResolvedPayload,
  TerminalInferenceUsage,
} from './messages';

export { EnvelopeSchema, isServerToDaemonType } from './envelope';
export type { Envelope } from './envelope';

export {
  ProtocolError,
  EnvelopeParseError,
  UnknownMessageTypeError,
  EnvelopeValidationError,
} from './errors';

export { encodeEnvelope, decodeEnvelope, createEnvelope, parseMessage } from './codec';
export type { CreateEnvelopeOptions } from './codec';

export {
  PairRequestSchema,
  PairResponseTenantIdSchema,
  PAIR_RESPONSE_TENANT_ID_MAX_LENGTH,
  PairResponseSchema,
  ChallengeRequestSchema,
  ChallengeResponseSchema,
  TokenRequestSchema,
  TokenResponseSchema,
  PresencePublishRequestSchema,
  CreateBlobRequestSchema,
  CreateBlobResponseSchema,
  BlobDownloadUrlResponseSchema,
  EventsPollQuerySchema,
  EventsPollResponseSchema,
  MessagesSendRequestSchema,
  MessagesSendResponseSchema,
  AgentHomeProjectionCompletionRequestSchema,
  AgentHomeProjectionStatusSchema,
  AgentHomeProjectionReadbackSchema,
  MAX_MESSAGES_PER_BATCH,
  BYOK_WS_PATH,
  BYOK_PAIR_PATH,
  BYOK_CHALLENGE_PATH,
  BYOK_TOKEN_PATH,
  BYOK_CAPABILITIES_PATH,
  BYOK_EVENTS_PATH,
  BYOK_MESSAGES_PATH,
  BYOK_AGENT_HOME_PROJECTIONS_PATH,
  BYOK_AGENT_HOME_PROJECTION_COMPLETION_ROUTE,
  byokAgentHomeProjectionCompletionPath,
  BYOK_PRESENCE_PATH,
  BYOK_ACTIVITY_PATH,
  BYOK_BOARD_PATH,
  BYOK_BOARD_STREAM_PATH,
  BYOK_BOARD_CLAIM_ROUTE,
  BYOK_BOARD_UNCLAIM_ROUTE,
  BYOK_BOARD_STATUS_ROUTE,
  BYOK_RECORDS_PATH,
  BYOK_RECORD_ROUTE,
  byokRecordPath,
  BYOK_SKILL_PACKS_PATH,
  BYOK_SKILL_PACK_FILE_ROUTE,
  byokSkillPackFilePath,
  BYOK_BLOBS_PATH,
  BYOK_BLOB_FINALIZE_ROUTE,
  BYOK_BLOB_URL_ROUTE,
  BYOK_BLOB_CONTENT_ROUTE,
  byokBlobFinalizePath,
  byokBlobUrlPath,
  byokBlobContentPath,
} from './http-api';
export type {
  PairRequest,
  PairResponse,
  ChallengeRequest,
  ChallengeResponse,
  TokenRequest,
  TokenResponse,
  PresencePublishRequest,
  CreateBlobRequest,
  CreateBlobResponse,
  BlobDownloadUrlResponse,
  EventsPollQuery,
  EventsPollResponse,
  MessagesSendRequest,
  MessagesSendResponse,
  AgentHomeProjectionCompletionRequest,
  AgentHomeProjectionStatus,
  AgentHomeProjectionReadback,
} from './http-api';
