import { chmodSync, existsSync } from 'node:fs';
import type { DatabaseSync } from 'node:sqlite';

import {
  PROVIDER_CONFIGURATION_LOCK_WAIT_MS,
  PROVIDER_CUSTODY_OPERATIONS,
  PROVIDER_CUSTODY_RECEIPT_LIMIT,
  ProcessLocalMutex,
  parseProviderProvisioningResult,
  type ProviderConfigurationLock,
  type ProviderCustodyCommit,
  type ProviderCustodyPending,
  type ProviderCustodyReceipt,
  type ProviderCustodyReservation,
  type ProviderKeyCheckOutcome,
} from './custody';
import { ByokKeysError } from './errors';
import {
  type ProviderProfileStore,
  providerNotConfigured,
} from './profile-store';
import {
  MODEL_PROVIDER_ADAPTERS,
  MODEL_PROVIDER_KINDS,
  PROVIDER_AUTH_MODES,
  type ModelProviderProfile,
  type ProviderProfileRef,
  parseModelProviderProfile,
} from './provider-profile';
import {
  closeSqliteDatabaseAfterInitializationFailure,
  loadSqliteModule,
  openSqliteDatabase,
  secureSqliteFilePermissions,
} from './sqlite-support';

export interface SqliteProviderProfileStoreOptions {
  /**
   * Database file path. `:memory:` exercises the SQLite code path without a
   * temp file, but defeats the point of this store (restart-safety) exactly as
   * it does for `@byok-sdk/server`'s `SqliteTaskStore`.
   */
  path: string;
  /** Open an existing profile database without creating or mutating it. */
  readOnly?: boolean;
  /**
   * How long {@link SqliteProviderProfileStore.acquireConfigurationLock} waits
   * for another process before failing closed with
   * `PROVIDER_CONFIGURATION_BUSY`. Defaults to
   * {@link PROVIDER_CONFIGURATION_LOCK_WAIT_MS}.
   */
  configurationLockWaitMs?: number;
}

/** SQL string-literal list for a CHECK constraint's `IN (...)` set. */
function sqlList(values: readonly string[]): string {
  return values.map((value) => `'${value}'`).join(', ');
}

/**
 * Ported from `providers.ts:109-140`, narrowed to the model branch. The
 * source's table also carried `market_data` / `mcp_http` rows and a `tool_name`
 * column; that branch stays in aip-main-open per
 * `docs/researches/HANDOFF-byok-keys.md` §4.5, so the CHECK constraints here
 * are the model half only.
 *
 * The three enumerated CHECK lists are generated from the schema authorities in
 * `provider-profile.ts` rather than restated here: `MODEL_PROVIDER_KINDS` (in
 * turn derived from `provider-catalog.ts`), `MODEL_PROVIDER_ADAPTERS`, and
 * `PROVIDER_AUTH_MODES`. A widened enum therefore cannot silently disagree with
 * a persisted table, and {@link assertProviderProfileSchemaIsCurrent} fails
 * closed on a database whose stored DDL was generated by a different version.
 */
const SCHEMA = `
CREATE TABLE IF NOT EXISTS provider_profile (
  profile_ref   TEXT PRIMARY KEY,
  provider_kind TEXT NOT NULL CHECK (provider_kind IN (${sqlList(MODEL_PROVIDER_KINDS)})),
  kind          TEXT NOT NULL CHECK (kind = 'model'),
  adapter       TEXT NOT NULL CHECK (adapter IN (${sqlList(MODEL_PROVIDER_ADAPTERS)})),
  display_name  TEXT NOT NULL,
  base_url      TEXT NOT NULL,
  auth_mode     TEXT NOT NULL CHECK (auth_mode IN (${sqlList(PROVIDER_AUTH_MODES)})),
  model         TEXT NOT NULL,
  pi_model      TEXT,
  capabilities  TEXT NOT NULL,
  enabled       INTEGER NOT NULL CHECK (enabled IN (0, 1)),
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
`;

/**
 * Compare a `CREATE TABLE` statement by shape rather than by byte: SQLite
 * stores the original statement text in `sqlite_master.sql` with `IF NOT
 * EXISTS` removed and the trailing semicolon dropped, so both sides are
 * stripped of those and their whitespace runs collapsed before comparison.
 */
function normalizeTableDdl(sql: string): string {
  return sql
    .replace(/\bIF\s+NOT\s+EXISTS\b/giu, '')
    .replace(/\s+/gu, ' ')
    .trim()
    .replace(/;$/u, '')
    .trim();
}

/**
 * Fail closed when the opened database's `provider_profile` table was created
 * by a different `@byok-sdk/keys` schema.
 *
 * `CREATE TABLE IF NOT EXISTS` is a no-op against an existing table, so a store
 * written by a version with a narrower `provider_kind` CHECK would otherwise
 * keep opening and only reject the new kind at `save` time, from inside a
 * transaction, as an opaque constraint violation. There is deliberately no
 * in-place migration: the local profile database holds declared configuration
 * the operator can retype, and a silent ALTER would be exactly the steady-state
 * compatibility path this package refuses. A database that does not carry the
 * table yet passes.
 */
function assertProviderProfileSchemaIsCurrent(
  database: DatabaseSync,
  path: string,
): void {
  const row = database
    .prepare(
      "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'provider_profile'",
    )
    .get() as { sql?: string | null } | undefined;
  const stored = row?.sql;
  if (typeof stored !== 'string') return;
  if (normalizeTableDdl(stored) === normalizeTableDdl(SCHEMA)) return;
  throw new ByokKeysError(
    'PROVIDER_STORE_SCHEMA_STALE',
    `Provider profile store at ${path} was created by a different @byok-sdk/keys schema; preserve this store and explicitly provision a separate current-schema store before continuing`,
  );
}

/**
 * The "at most one enabled profile" invariant, enforced by the database itself
 * rather than only by {@link SqliteProviderProfileStore.save}
 * (`providers.ts:140-144`). A partial unique index means a bug in the write
 * path surfaces as a constraint violation instead of silently producing two
 * defaults.
 */
const ENABLED_INDEX = `
CREATE UNIQUE INDEX IF NOT EXISTS provider_profile_one_enabled
ON provider_profile(kind)
WHERE enabled = 1;
`;

/**
 * Credential-custody state (`custody.ts`), in the same database as the
 * profiles so the final custody write — profile mutation, receipt, watermark,
 * pending clear — is one SQLite transaction. None of these tables holds a
 * secret.
 */
const CUSTODY_TABLES: Readonly<Record<string, string>> = {
  provider_custody_pending: `
CREATE TABLE IF NOT EXISTS provider_custody_pending (
  profile_ref          TEXT PRIMARY KEY,
  operation            TEXT NOT NULL CHECK (operation IN (${sqlList(PROVIDER_CUSTODY_OPERATIONS)})),
  request_id           TEXT,
  request_digest       TEXT,
  operation_generation INTEGER CHECK (operation_generation IS NULL OR operation_generation > 0),
  since                TEXT NOT NULL,
  CHECK ((request_id IS NULL) = (request_digest IS NULL))
);
`,
  provider_custody_reservation: `
CREATE TABLE IF NOT EXISTS provider_custody_reservation (
  request_id           TEXT PRIMARY KEY,
  request_digest       TEXT NOT NULL,
  profile_ref          TEXT NOT NULL,
  operation_generation INTEGER NOT NULL CHECK (operation_generation > 0)
);
`,
  provider_custody_watermark: `
CREATE TABLE IF NOT EXISTS provider_custody_watermark (
  profile_ref          TEXT PRIMARY KEY,
  operation_generation INTEGER NOT NULL CHECK (operation_generation > 0)
);
`,
  provider_custody_receipt: `
CREATE TABLE IF NOT EXISTS provider_custody_receipt (
  seq                  INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id           TEXT NOT NULL UNIQUE,
  profile_ref          TEXT NOT NULL,
  operation_generation INTEGER NOT NULL CHECK (operation_generation > 0),
  request_digest       TEXT NOT NULL,
  result               TEXT NOT NULL
);
`,
};

/** Sibling file whose SQLite EXCLUSIVE lock is the cross-process configuration lock. */
export function providerConfigurationLockPath(databasePath: string): string {
  return `${databasePath}.config-lock`;
}

/**
 * Fail closed unless every custody table exists with exactly this version's
 * DDL. A read-only open (the launcher) cannot create them, and cannot prove
 * the absence of a pending marker without them, so a missing table is stale.
 */
function assertCustodySchemaIsCurrent(database: DatabaseSync, path: string): void {
  for (const [name, ddl] of Object.entries(CUSTODY_TABLES)) {
    const row = database
      .prepare("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?")
      .get(name) as { sql?: string | null } | undefined;
    const stored = row?.sql;
    if (typeof stored === 'string' && normalizeTableDdl(stored) === normalizeTableDdl(ddl)) continue;
    throw new ByokKeysError(
      'PROVIDER_STORE_SCHEMA_STALE',
      `Provider profile store at ${path} lacks the current credential-custody schema; open it once with this @byok-sdk/keys version in writable mode before reading credentials`,
    );
  }
}

/**
 * Lock connections currently held by this process. Holding them here keeps
 * each one strongly reachable until `release`, independent of how a caller
 * holds the lock object: a runtime that collects an unreachable connection
 * (observed with Bun) would otherwise finalize it and drop the lock early.
 */
const HELD_LOCK_CONNECTIONS = new Set<DatabaseSync>();

function isSqliteBusy(error: unknown): boolean {
  const code = (error as { errcode?: unknown } | null)?.errcode;
  return code === 5 || code === 6;
}

function sleep(milliseconds: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

interface PendingRow {
  operation: string;
  operation_generation: number | null;
  profile_ref: string;
  request_digest: string | null;
  request_id: string | null;
  since: string;
}

interface ReservationRow {
  operation_generation: number;
  profile_ref: string;
  request_digest: string;
  request_id: string;
}

interface ReceiptRow {
  operation_generation: number;
  profile_ref: string;
  request_digest: string;
  request_id: string;
  result: string;
}

interface ProfileRow {
  adapter: string;
  auth_mode: string;
  base_url: string;
  capabilities: string;
  created_at: string;
  display_name: string;
  enabled: number;
  kind: string;
  model: string;
  pi_model: string | null;
  profile_ref: string;
  provider_kind: string;
  updated_at: string;
}

/**
 * SQLite-backed {@link ProviderProfileStore}, following `@byok-sdk/server`'s
 * `SqliteTaskStore` shape. Holds no secret: the API key lives in the injected
 * `SecretStore`, and `registry.golden.test.ts` asserts the plaintext key never
 * appears in this file's bytes.
 */
export class SqliteProviderProfileStore implements ProviderProfileStore {
  readonly #database: DatabaseSync;
  readonly #path: string;
  readonly #mutex = new ProcessLocalMutex();
  readonly #lockWaitMs: number;
  #closed = false;

  constructor(options: SqliteProviderProfileStoreOptions) {
    this.#path = options.path;
    this.#lockWaitMs = options.configurationLockWaitMs ?? PROVIDER_CONFIGURATION_LOCK_WAIT_MS;
    if (!Number.isSafeInteger(this.#lockWaitMs) || this.#lockWaitMs < 0) {
      throw new ByokKeysError('PROVIDER_STORE_UNAVAILABLE', 'configurationLockWaitMs must be a non-negative integer');
    }
    this.#database = openSqliteDatabase(options.path, {
      readOnly: options.readOnly ?? false,
    });
    if (!options.readOnly) {
      try {
        this.#database.exec(SCHEMA);
        this.#database.exec(ENABLED_INDEX);
        for (const ddl of Object.values(CUSTODY_TABLES)) this.#database.exec(ddl);
        assertProviderProfileSchemaIsCurrent(this.#database, options.path);
        assertCustodySchemaIsCurrent(this.#database, options.path);
        secureSqliteFilePermissions(options.path);
        ensureConfigurationLockFile(options.path);
      } catch (error) {
        closeSqliteDatabaseAfterInitializationFailure(
          this.#database,
          error,
          'SqliteProviderProfileStore initialization failed and its native handle could not be closed',
        );
      }
    } else {
      try {
        assertProviderProfileSchemaIsCurrent(this.#database, options.path);
        assertCustodySchemaIsCurrent(this.#database, options.path);
      } catch (error) {
        closeSqliteDatabaseAfterInitializationFailure(
          this.#database,
          error,
          'SqliteProviderProfileStore read-only schema check failed and its native handle could not be closed',
        );
      }
    }
  }

  /**
   * Idempotent, as {@link ProviderProfileStore.close} requires: `node:sqlite`
   * throws "database is not open" on a second `close()`, and a store is
   * routinely closed both by the code that finished with it and by a test's
   * teardown.
   */
  async close(): Promise<void> {
    if (this.#closed) return;
    this.#closed = true;
    this.#database.close();
  }

  async delete(profileRef: ProviderProfileRef): Promise<boolean> {
    const result = this.#database
      .prepare('DELETE FROM provider_profile WHERE profile_ref = ?')
      .run(profileRef);
    return Number(result.changes) === 1;
  }

  async get(profileRef: ProviderProfileRef): Promise<ModelProviderProfile | undefined> {
    const row = this.#database
      .prepare('SELECT * FROM provider_profile WHERE profile_ref = ?')
      .get(profileRef) as ProfileRow | undefined;
    return row === undefined ? undefined : parseRow(row);
  }

  async getEnabled(): Promise<ModelProviderProfile | undefined> {
    const row = this.#database
      .prepare('SELECT * FROM provider_profile WHERE enabled = 1')
      .get() as ProfileRow | undefined;
    return row === undefined ? undefined : parseRow(row);
  }

  async list(): Promise<ModelProviderProfile[]> {
    const rows = this.#database
      .prepare('SELECT * FROM provider_profile ORDER BY profile_ref ASC')
      .all() as unknown as ProfileRow[];
    return rows.map(parseRow);
  }

  async save(profile: ModelProviderProfile): Promise<ModelProviderProfile> {
    const validated = await this.#validateForSave(profile);
    this.#transaction(() => this.#writeProfile(validated));
    return (await this.get(validated.profile_ref)) as ModelProviderProfile;
  }

  async #validateForSave(profile: ModelProviderProfile): Promise<ModelProviderProfile> {
    const existing = await this.get(profile.profile_ref);
    return parseModelProviderProfile({
      ...profile,
      created_at: existing?.created_at ?? profile.created_at,
    });
  }

  #writeProfile(validated: ModelProviderProfile): void {
      if (validated.enabled) {
        this.#database
          .prepare(
            'UPDATE provider_profile SET enabled = 0 WHERE profile_ref <> ?',
          )
          .run(validated.profile_ref);
      }
      this.#database
        .prepare(
          `INSERT INTO provider_profile (
             profile_ref, provider_kind, kind, adapter, display_name, base_url,
             auth_mode, model, pi_model, capabilities, enabled, created_at, updated_at
           ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(profile_ref) DO UPDATE SET
             provider_kind = excluded.provider_kind,
             adapter = excluded.adapter,
             display_name = excluded.display_name,
             base_url = excluded.base_url,
             auth_mode = excluded.auth_mode,
             model = excluded.model,
             pi_model = excluded.pi_model,
             capabilities = excluded.capabilities,
             enabled = excluded.enabled,
             updated_at = excluded.updated_at`,
        )
        .run(
          validated.profile_ref,
          validated.provider_kind,
          validated.kind,
          validated.adapter,
          validated.display_name,
          validated.base_url,
          validated.auth_mode,
          validated.model,
          validated.pi_model === undefined ? null : JSON.stringify(validated.pi_model),
          JSON.stringify(validated.capabilities),
          validated.enabled ? 1 : 0,
          validated.created_at,
          validated.updated_at,
        );
  }

  /**
   * Cross-process for a file database: an EXCLUSIVE transaction on the
   * sibling lock file, which the operating system releases if this process
   * dies. Acquisition polls without blocking the event loop and fails closed
   * after the configured wait. The lock connection stays strongly referenced
   * until `release`, so a garbage collector can never finalize it early (Bun
   * collects unreachable connections).
   */
  async acquireConfigurationLock(): Promise<ProviderConfigurationLock> {
    const local = await this.#mutex.acquire();
    if (this.#path === ':memory:') return local;
    let lockDatabase: DatabaseSync | undefined;
    try {
      const lockPath = providerConfigurationLockPath(this.#path);
      if (!existsSync(lockPath)) {
        throw new ByokKeysError(
          'PROVIDER_STORE_SCHEMA_STALE',
          `Provider profile store at ${this.#path} has no credential-custody lock file; open it once in writable mode first`,
        );
      }
      const { DatabaseSync } = loadSqliteModule();
      // Read-write even for a read-only profile store: a read-only SQLite
      // connection can hold only a SHARED lock, which would not exclude
      // another reader. The file already exists, so nothing is created.
      lockDatabase = new DatabaseSync(lockPath, { timeout: 0 });
      const deadline = Date.now() + this.#lockWaitMs;
      for (;;) {
        try {
          lockDatabase.exec('BEGIN EXCLUSIVE');
          break;
        } catch (error) {
          if (!isSqliteBusy(error)) throw error;
          if (Date.now() >= deadline) {
            throw new ByokKeysError('PROVIDER_CONFIGURATION_BUSY', 'Provider configuration lock is held by another process');
          }
          await sleep(20);
        }
      }
    } catch (error) {
      lockDatabase?.close();
      await local.release();
      throw error;
    }
    const held = lockDatabase;
    HELD_LOCK_CONNECTIONS.add(held);
    let released = false;
    return {
      release: async () => {
        if (released) return;
        released = true;
        try {
          held.exec('ROLLBACK');
        } finally {
          HELD_LOCK_CONNECTIONS.delete(held);
          held.close();
          await local.release();
        }
      },
    };
  }

  async getPending(profileRef: ProviderProfileRef): Promise<ProviderCustodyPending | undefined> {
    const row = this.#database
      .prepare('SELECT * FROM provider_custody_pending WHERE profile_ref = ?')
      .get(profileRef) as PendingRow | undefined;
    if (row === undefined) return undefined;
    return {
      profileRef: row.profile_ref,
      operation: row.operation as ProviderCustodyPending['operation'],
      requestId: row.request_id,
      requestDigest: row.request_digest,
      operationGeneration: row.operation_generation === null ? null : Number(row.operation_generation),
      since: row.since,
    };
  }

  async getReservation(requestId: string): Promise<ProviderCustodyReservation | undefined> {
    const row = this.#database
      .prepare('SELECT * FROM provider_custody_reservation WHERE request_id = ?')
      .get(requestId) as ReservationRow | undefined;
    return row === undefined
      ? undefined
      : {
        requestId: row.request_id,
        requestDigest: row.request_digest,
        profileRef: row.profile_ref,
        operationGeneration: Number(row.operation_generation),
      };
  }

  async markPending(pending: ProviderCustodyPending): Promise<void> {
    if ((pending.requestId === null) !== (pending.requestDigest === null)
      || (pending.requestId !== null && pending.operationGeneration === null)) {
      throw new ByokKeysError('PROVIDER_CUSTODY_STATE_INVALID', 'A provisioning pending marker requires request id, digest and generation together');
    }
    this.#transaction(() => {
      if (pending.requestId !== null) {
        // Store-wide request identity, in the same transaction as the marker
        // and the watermark: one digest per id, never over a receipt.
        const receipt = this.#database
          .prepare('SELECT 1 AS present FROM provider_custody_receipt WHERE request_id = ?')
          .get(pending.requestId);
        const existing = this.#database
          .prepare('SELECT request_digest FROM provider_custody_reservation WHERE request_id = ?')
          .get(pending.requestId) as { request_digest: string } | undefined;
        if (receipt !== undefined || (existing !== undefined && existing.request_digest !== pending.requestDigest)) {
          throw new ByokKeysError('PROVIDER_CUSTODY_STATE_INVALID', 'Provisioning request id is already reserved');
        }
        this.#database
          .prepare(
            `INSERT INTO provider_custody_reservation (request_id, request_digest, profile_ref, operation_generation)
             VALUES (?, ?, ?, ?)
             ON CONFLICT(request_id) DO NOTHING`,
          )
          .run(pending.requestId, pending.requestDigest, pending.profileRef, pending.operationGeneration);
      }
      this.#database
        .prepare(
          `INSERT INTO provider_custody_pending (profile_ref, operation, request_id, request_digest, operation_generation, since)
           VALUES (?, ?, ?, ?, ?, ?)
           ON CONFLICT(profile_ref) DO UPDATE SET
             operation = excluded.operation,
             request_id = excluded.request_id,
             request_digest = excluded.request_digest,
             operation_generation = excluded.operation_generation,
             since = excluded.since`,
        )
        .run(pending.profileRef, pending.operation, pending.requestId, pending.requestDigest, pending.operationGeneration, pending.since);
      if (pending.operationGeneration !== null) this.#raiseWatermark(pending.profileRef, pending.operationGeneration);
    });
  }

  async getOperationWatermark(profileRef: ProviderProfileRef): Promise<number | undefined> {
    const row = this.#database
      .prepare('SELECT operation_generation FROM provider_custody_watermark WHERE profile_ref = ?')
      .get(profileRef) as { operation_generation: number } | undefined;
    return row === undefined ? undefined : Number(row.operation_generation);
  }

  async getReceipt(requestId: string): Promise<ProviderCustodyReceipt | undefined> {
    const row = this.#database
      .prepare('SELECT * FROM provider_custody_receipt WHERE request_id = ?')
      .get(requestId) as ReceiptRow | undefined;
    return row === undefined ? undefined : parseReceiptRow(row);
  }

  async commitCustody(commit: ProviderCustodyCommit): Promise<void> {
    const profile = commit.mutation.kind === 'save' ? await this.#validateForSave(commit.mutation.profile) : undefined;
    this.#transaction(() => {
      if (profile !== undefined) this.#writeProfile(profile);
      if (commit.mutation.kind === 'delete') {
        this.#database.prepare('DELETE FROM provider_profile WHERE profile_ref = ?').run(commit.profileRef);
      }
      if (commit.receipt !== undefined) this.#writeReceipt(commit.receipt);
      if (commit.clearPending) {
        this.#database.prepare('DELETE FROM provider_custody_pending WHERE profile_ref = ?').run(commit.profileRef);
      }
    });
  }

  async recordKeyCheck(requestId: string, operationGeneration: number, keyCheck: ProviderKeyCheckOutcome): Promise<boolean> {
    let recorded = false;
    this.#transaction(() => {
      const row = this.#database
        .prepare('SELECT * FROM provider_custody_receipt WHERE request_id = ?')
        .get(requestId) as ReceiptRow | undefined;
      if (row === undefined || Number(row.operation_generation) !== operationGeneration) return;
      const watermark = this.#database
        .prepare('SELECT operation_generation FROM provider_custody_watermark WHERE profile_ref = ?')
        .get(row.profile_ref) as { operation_generation: number } | undefined;
      if (watermark === undefined || Number(watermark.operation_generation) !== operationGeneration) return;
      const receipt = parseReceiptRow(row);
      this.#database
        .prepare('UPDATE provider_custody_receipt SET result = ? WHERE request_id = ?')
        .run(JSON.stringify({ ...receipt.result, keyCheck }), requestId);
      recorded = true;
    });
    return recorded;
  }

  #raiseWatermark(profileRef: ProviderProfileRef, operationGeneration: number): void {
    this.#database
      .prepare(
        `INSERT INTO provider_custody_watermark (profile_ref, operation_generation) VALUES (?, ?)
         ON CONFLICT(profile_ref) DO UPDATE SET
           operation_generation = MAX(provider_custody_watermark.operation_generation, excluded.operation_generation)`,
      )
      .run(profileRef, operationGeneration);
  }

  #writeReceipt(receipt: ProviderCustodyReceipt): void {
    this.#database
      .prepare(
        `INSERT INTO provider_custody_receipt (request_id, profile_ref, operation_generation, request_digest, result)
         VALUES (?, ?, ?, ?, ?)`,
      )
      .run(receipt.requestId, receipt.profileRef, receipt.operationGeneration, receipt.requestDigest, JSON.stringify(receipt.result));
    this.#raiseWatermark(receipt.profileRef, receipt.operationGeneration);
    this.#database.prepare('DELETE FROM provider_custody_reservation WHERE request_id = ?').run(receipt.requestId);
    this.#database
      .prepare(
        `DELETE FROM provider_custody_receipt
         WHERE seq <= (SELECT MAX(seq) FROM provider_custody_receipt) - ?`,
      )
      .run(PROVIDER_CUSTODY_RECEIPT_LIMIT);
  }

  async setEnabled(profileRef: ProviderProfileRef): Promise<ModelProviderProfile> {
    const existing = await this.get(profileRef);
    if (existing === undefined) throw providerNotConfigured(profileRef);
    return this.save({ ...existing, enabled: true });
  }

  /** `BEGIN IMMEDIATE` / `COMMIT` / `ROLLBACK`, per `providers.ts:1252-1263`. */
  #transaction(body: () => void): void {
    this.#database.exec('BEGIN IMMEDIATE');
    try {
      body();
      this.#database.exec('COMMIT');
    } catch (error) {
      this.#database.exec('ROLLBACK');
      throw error;
    }
  }
}

/**
 * Rows go back through the same zod schema the write path used, so a row that
 * a different process wrote — or an older schema left behind — is rejected
 * rather than trusted. `enabled` is an INTEGER in SQLite and a real boolean in
 * the schema, and `capabilities` is a JSON array in a TEXT column, so both are
 * decoded explicitly and a row that fails to decode is refused rather than
 * quietly downgraded to an empty capability set.
 */
function parseRow(row: ProfileRow): ModelProviderProfile {
  let capabilities: unknown;
  try {
    capabilities = JSON.parse(row.capabilities);
  } catch (cause) {
    throw new ByokKeysError(
      'PROVIDER_PROFILE_INVALID',
      'Provider profile capabilities column is not valid JSON',
      { cause },
    );
  }
  return parseModelProviderProfile({
    ...row,
    pi_model: row.pi_model === null ? undefined : JSON.parse(row.pi_model),
    capabilities,
    enabled: row.enabled === 1,
  });
}

function parseReceiptRow(row: ReceiptRow): ProviderCustodyReceipt {
  let result: unknown;
  try {
    result = JSON.parse(row.result);
  } catch {
    throw new ByokKeysError('PROVIDER_CUSTODY_STATE_INVALID', 'Stored provider provisioning result is not valid JSON');
  }
  return {
    requestId: row.request_id,
    profileRef: row.profile_ref,
    operationGeneration: Number(row.operation_generation),
    requestDigest: row.request_digest,
    result: parseProviderProvisioningResult(result),
  };
}

/** Create the sibling lock file owner-only, once, from a writable open. No-op for `:memory:`. */
function ensureConfigurationLockFile(databasePath: string): void {
  if (databasePath === ':memory:') return;
  const lockPath = providerConfigurationLockPath(databasePath);
  if (!existsSync(lockPath)) {
    const { DatabaseSync } = loadSqliteModule();
    new DatabaseSync(lockPath).close();
  }
  chmodSync(lockPath, 0o600);
}

/** Exported for the store's own tests to enumerate the CHECK-constrained kinds. */
export const SQLITE_PROFILE_PROVIDER_KINDS = MODEL_PROVIDER_KINDS;
