import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import {build} from 'esbuild';
import {Miniflare} from 'miniflare';
import {canonicalArgs} from '../src/tools';
import {admitCloudInbox,INBOX_DAY} from '../src/inbox-admission';
import type {InboxRow,CloudEventRow,CloudEventMeta,RunRow} from '../src/cloud-state';
let mf:Miniflare;let persist:string;let script:string;
const now=Date.now()+600_000;
function runtime() {return new Miniflare({resourcePersistencePath:persist,workers:[{config:{name:'cloud-state-test',type:'worker',compatibilityDate:'2026-08-18',compatibilityFlags:['no_nodejs_compat','no_nodejs_compat_v2'],manifest:{mainModule:'worker.js',modules:{'worker.js':{type:'esm',contents:script}}},exports:{CloudStateDO:{type:'durable-object',storage:'sqlite'}},env:{STATES:{type:'durable-object',workerName:'cloud-state-test',exportName:'CloudStateDO'}}}}]});}
beforeAll(async()=>{script=(await build({entryPoints:[path.resolve(import.meta.dirname,'cloud-state-worker.ts')],bundle:true,format:'esm',platform:'browser',external:['cloudflare:workers'],write:false})).outputFiles![0]!.text;persist=await mkdtemp(path.join(os.tmpdir(),'byok-cloud-state-'));mf=runtime();await mf.ready;});
afterAll(async()=>{await mf?.dispose();if(persist) await rm(persist,{recursive:true,force:true});});
async function rpc<T>(name:string,op:string,args:Record<string,unknown>={}):Promise<T> {const response=await mf.dispatchFetch('http://test/',{method:'POST',body:JSON.stringify({name,op,now,...args})});const body=await response.json() as T;if(!response.ok) throw new Error((body as {error:{code:string}}).error.code);return body;}
const enqueue=(name:string,dedupKey:string,args:Record<string,unknown>={})=>rpc<{accepted:boolean;row:InboxRow}>(name,'enqueue',{input:{dedupKey,source:'message',text:'ordinary',...args}});

describe('cloud state in actual workerd SQLite',()=>{
  it('adds execution columns to the existing ledger schema without arming an alarm',async()=>{const result=await rpc<{columns:string[];alarm:number|null}>('schema','schema');expect(result.columns).toEqual(expect.arrayContaining(['trigger','requestId','submissionId','state','reservation','eligibilityJson']));expect(result.alarm).toBeNull();});
  it('rejects unknown fields and invalid times before writes',async()=>{for(const extra of [{metadata:{}},{availableAt:now+30*INBOX_DAY+1},{availableAt:1.5},{availableAt:now,expiresAt:now},{source:'unknown'}]) await expect(enqueue('invalid','one',extra)).rejects.toThrow('CLOUD_REQUEST_INVALID');expect(await rpc('invalid','events')).toEqual([]);expect(await rpc('invalid','alarm')).toBeNull();});
  it('retains first defaults and compares a real SHA-256 digest on retries',async()=>{const a=await enqueue('dedup','one');const b=await rpc<{accepted:boolean;row:InboxRow}>('dedup','enqueue',{now:now+1000,input:{dedupKey:'one',source:'message',text:'ordinary'}});expect(b).toEqual({accepted:false,row:a.row});expect(a.row.payloadDigest).toBe(createHash('sha256').update(canonicalArgs({source:'message',text:'ordinary',profile:'zai_openai',availableAt:now,expiresAt:now+INBOX_DAY})).digest('hex'));await expect(enqueue('dedup','one',{expiresAt:now+2*INBOX_DAY})).rejects.toThrow('CLOUD_INBOX_CONFLICT');await expect(enqueue('dedup','one',{availableAt:now+2*INBOX_DAY})).rejects.toThrow('CLOUD_INBOX_CONFLICT');expect(await rpc('dedup','events')).toHaveLength(1);expect(await rpc('dedup','alarm')).toBe(now);});
  it('deduplicates an explicit expiry after time advances when availability was omitted',async()=>{
    const item={dedupKey:'expiry',source:'message',text:'ordinary',expiresAt:now+1000};
    const first=await rpc<{accepted:boolean;row:InboxRow}>('expiry-default-retry','enqueue',{input:item});
    await rpc('expiry-default-retry','cancel',{seq:first.row.seq});
    const before=await rpc<CloudEventRow[]>('expiry-default-retry','events');
    const replay=await rpc<{accepted:boolean;row:InboxRow}>('expiry-default-retry','enqueue',{input:item,now:now+2000});
    expect(replay.accepted).toBe(false);expect(replay.row).toMatchObject({availableAt:now,expiresAt:now+1000,state:'cancelled'});
    expect(await rpc('expiry-default-retry','events')).toEqual(before);
    await expect(rpc('expiry-new-invalid','enqueue',{input:item,now:now+2000})).rejects.toThrow('CLOUD_REQUEST_INVALID');
    expect(await rpc('expiry-new-invalid','events')).toEqual([]);
    expect(await rpc('expiry-new-invalid','alarm')).toBeNull();
  });
  it('rolls back both state and event on a real SQLite transaction failure',async()=>{const {row}=await enqueue('rollback','one');const result=await rpc<{row:InboxRow;events:CloudEventRow[]}>('rollback','rollback',{seq:row.seq});expect(result.row.state).toBe('queued');expect(result.events.map(row=>row.eventKey)).toEqual([`inbox:${row.seq}:accepted`]);});
  it('keeps A B A as three contiguous groups and resolves equal times by seq',async()=>{const a=await enqueue('profiles','a');const b=await enqueue('profiles','b',{profile:'deepseek_direct'});const c=await enqueue('profiles','c');expect((await rpc<InboxRow[]>('profiles','select')).map(row=>row.seq)).toEqual([a.row.seq]);await rpc('profiles','cancel',{seq:a.row.seq});expect((await rpc<InboxRow[]>('profiles','select')).map(row=>row.seq)).toEqual([b.row.seq]);await rpc('profiles','cancel',{seq:b.row.seq});expect((await rpc<InboxRow[]>('profiles','select')).map(row=>row.seq)).toEqual([c.row.seq]);});
  it('measures complete encoded input and fails a single expanding item without claim',async()=>{const {row}=await enqueue('budget','one',{text:'x'+'\u0001'.repeat(15999)});expect(await rpc('budget','select')).toEqual([]);expect(await rpc('budget','read',{seq:row.seq})).toMatchObject({state:'failed',attempts:0,payloadJson:null,errorCode:'CLOUD_INBOX_TOO_LARGE'});const a=await enqueue('multibyte','one',{text:'界'.repeat(7990)});await enqueue('multibyte','two',{text:'界'.repeat(7990)});expect((await rpc<InboxRow[]>('multibyte','select')).map(item=>item.seq)).toEqual([a.row.seq]);});
  it('makes a pre-mark recovery snapshot immutable across workerd restarts',async()=>{await rpc('eligibility','start',{id:1});expect(await rpc('eligibility','eligible')).toMatchObject([{eligibilityJson:'{"steps":0,"aborted":0,"fatalCode":null,"wasStale":false}'}]);await rpc('eligibility','mark',{id:1});await mf.dispose();mf=runtime();await mf.ready;expect(await rpc('eligibility','eligible')).toMatchObject([{fatalCode:'CLOUD_EXECUTION_INTERRUPTED',eligibilityJson:'{"steps":0,"aborted":0,"fatalCode":null,"wasStale":false}'}]);});
  it('preserves original stale evidence when a second workerd instance sees no stale runs',async()=>{const name='stale-snapshot';const {row}=await enqueue(name,'one');await rpc(name,'start',{id:1});await rpc(name,'claim',{id:1,seqs:[row.seq]});const before=await rpc<RunRow[]>(name,'eligible',{stale:[1]});expect(before).toMatchObject([{state:'running',eligibilityJson:'{"steps":0,"aborted":0,"fatalCode":null,"wasStale":true}'}]);await rpc(name,'mark',{id:1});await mf.dispose();mf=runtime();await mf.ready;const after=await rpc<RunRow[]>(name,'eligible',{stale:[]});expect(after).toMatchObject([{state:'running',fatalCode:'CLOUD_EXECUTION_INTERRUPTED',eligibilityJson:before[0]!.eligibilityJson}]);expect(JSON.parse(after[0]!.eligibilityJson!)).toEqual({steps:0,aborted:0,fatalCode:null,wasStale:true});});
  it('requeues zero-step claims three times and fails the fourth claim',async()=>{const {row}=await enqueue('attempts','one');for(let id=1;id<=4;id++){await rpc('attempts','start',{id});const claimed=await rpc<InboxRow[]>('attempts','claim',{id,seqs:[row.seq]});if(id<4){expect(claimed).toHaveLength(1);await rpc('attempts','settle',{id,outcome:'interrupted'});}else expect(claimed).toEqual([]);}expect(await rpc('attempts','read',{seq:row.seq})).toMatchObject({state:'failed',attempts:4,payloadJson:null,errorCode:'CLOUD_WAKE_EXHAUSTED'});});
  it('settles a run and releases a committed reservation once',async()=>{const {row}=await enqueue('settle','one');await rpc('settle','start',{id:1});await rpc('settle','reserve',{id:1});await rpc('settle','claim',{id:1,seqs:[row.seq]});const first=await rpc<RunRow>('settle','settle',{id:1,text:'answer'});expect(first.state).toBe('completed');expect(first.reservation).toBe('released');await rpc('settle','settle',{id:1,text:'answer'});expect(await rpc('settle','read',{seq:row.seq})).toMatchObject({state:'done',payloadJson:null});const events=await rpc<CloudEventRow[]>('settle','events');expect(events.filter(row=>row.type==='run.completed')).toHaveLength(1);expect(events.filter(row=>row.type==='run.reservation'&&JSON.parse(row.dataJson).action==='release')).toHaveLength(1);});
  it('uses expiry for queue admission and interrupted requeue without replacing a claimed run outcome',async()=>{for(const [outcome,state,code] of [['completed','done',null],['failed','failed','CLOUD_MODEL_REQUEST_FAILED'],['interrupted','expired','CLOUD_INBOX_EXPIRED']]){const name=`claimed-expiry-${outcome}`;const {row}=await enqueue(name,'one',{expiresAt:now+1});await rpc(name,'start',{id:1});expect(await rpc(name,'claim',{id:1,seqs:[row.seq]})).toHaveLength(1);await rpc(name,'settle',{id:1,outcome,now:now+2});expect(await rpc(name,'read',{seq:row.seq})).toMatchObject({state,errorCode:code,payloadJson:null});const events=await rpc<CloudEventRow[]>(name,'events');expect(JSON.parse(events.find(event=>event.type==='inbox.settled')!.dataJson)).toMatchObject({state,errorCode:code});}});
  it('checks projection keys and decoded Unicode through the awaited production guard',async()=>{for(const projection of ['key-secret','decoded-secret','decoded-key-secret']){const result=await rpc<{rows:Array<{errorCode:string}>;events:CloudEventRow[]}>(`guard-${projection}`,'projection',{projection});expect(result.rows).toHaveLength(1);expect(result.rows[0]!.errorCode).toBe('CLOUD_PROJECTION_FAILED');expect(result.events.map(row=>row.type)).toEqual(['projection.failed']);expect(await rpc(`guard-${projection}`,'audit')).toEqual({leak:false});}});
  it('rejects excessive raw JSON before the production guard can reduce it to a small value',async()=>{for(const projection of ['raw-oversized','raw-multibyte']){const result=await rpc<{rows:Array<{errorCode:string}>;events:CloudEventRow[]}>(`cap-${projection}`,'projection',{projection});expect(result.rows).toHaveLength(1);expect(result.rows[0]!.errorCode).toBe('CLOUD_PROJECTION_FAILED');expect(result.events.map(event=>event.type)).toEqual(['projection.failed']);}const boundary=await rpc<{rows:Array<{errorCode:string|null}>;events:CloudEventRow[]}>('cap-boundary','projection',{projection:'raw-boundary'});expect(boundary.rows).toHaveLength(1);expect(boundary.rows[0]!.errorCode).toBeNull();expect(boundary.events.map(event=>event.type)).toEqual(['projection']);});
  it('stores native numeric task and result ids with real SQLite INTEGER affinity',async()=>{const result=await rpc<{column:string;row:{taskId:number;taskType:string;entryType:string}}>('delivery-type','delivery-type');expect(result).toEqual({column:'INTEGER',row:{taskId:42,taskType:'integer',entryType:'integer'}});});
  it('captures consumer projection strings once before guard and persistence',async()=>{
    const result=await rpc<{rows:Array<{key:string;errorCode:string|null}>;events:CloudEventRow[];keyReads:number;dataReads:number}>('projection-capture','projection',{projection:'capture-once'});
    expect(result.keyReads).toBe(1);expect(result.dataReads).toBe(1);
    expect(result.rows).toMatchObject([{key:'projection:invocation:captured',errorCode:null}]);
    expect(result.events.map(event=>event.type)).toEqual(['projection']);
    expect(await rpc('projection-capture','audit')).toEqual({leak:false});
  });
  it('namespaces projection keys per invocation and marks a changed digest once',async()=>{const name='projections';await rpc(name,'projection',{invocationId:'one'});await rpc(name,'projection',{invocationId:'two'});await rpc(name,'projection',{invocationId:'one'});await rpc(name,'projection',{invocationId:'one',projection:'changed'});const result=await rpc<{rows:unknown[];events:CloudEventRow[]}>(name,'projection',{invocationId:'one',projection:'changed'});expect(result.rows).toHaveLength(3);expect(result.events.map(row=>row.type)).toEqual(['projection','projection','projection.failed']);});
  it('advances retained boundaries in batches and keeps highWater when all events expire',async()=>{await rpc('retention','event-batch',{count:650,now:now-8*INBOX_DAY});expect(await rpc('retention','retention')).toEqual({events:500,inbox:0});const meta=await rpc<CloudEventMeta>('retention','meta');expect(meta).toEqual({trimmedThrough:500,highWater:650});await expect(rpc('retention','events',{after:499})).rejects.toThrow('CLOUD_EVENT_CURSOR_EXPIRED');expect(await rpc('retention','events',{after:500})).toHaveLength(100);expect(await rpc('retention','retention')).toEqual({events:150,inbox:0});expect(await rpc('retention','meta')).toEqual({trimmedThrough:650,highWater:650});expect(await rpc('retention','events')).toEqual([]);await expect(rpc('retention','events',{after:651})).rejects.toThrow('CLOUD_EVENT_CURSOR_EXPIRED');});
  it('enforces the 10000 event hard cap during one multi-event transaction',async()=>{const result=await rpc<{count:number;meta:CloudEventMeta}>('hard-cap','event-batch',{count:10005});expect(result.count).toBe(9505);expect(result.meta).toEqual({trimmedThrough:500,highWater:10005});});
  it('keeps terminal dedup keys for seven days then accepts the same key again',async()=>{const name='dedup-window';const first=await enqueue(name,'one');await rpc(name,'cancel',{seq:first.row.seq});const retry=await rpc<{accepted:boolean}>(name,'enqueue',{now:now+(7*INBOX_DAY-1),input:{dedupKey:'one',source:'message',text:'ordinary'}});expect(retry.accepted).toBe(false);const fresh=await rpc<{accepted:boolean;row:InboxRow}>(name,'enqueue',{now:now+7*INBOX_DAY,input:{dedupKey:'one',source:'message',text:'ordinary'}});expect(fresh.accepted).toBe(true);expect(fresh.row.seq).toBeGreaterThan(first.row.seq);});
  it('writes only a bounded preview and never writes a rejected final text',async()=>{for(const [name,text] of [['preview','界'.repeat(24000)],['rejected-final','CloudStatePlatformSecret0123456789Aa']]){const row=(await enqueue(name!,'one')).row;await rpc(name!,'start',{id:1});await rpc(name!,'claim',{id:1,seqs:[row.seq]});await rpc(name!,'settle',{id:1,text});const event=(await rpc<CloudEventRow[]>(name!,'events')).find(row=>row.type==='run.completed')!;const data=JSON.parse(event.dataJson);if(name==='preview'){expect(data.truncated).toBe(true);expect(Buffer.byteLength(data.text)).toBeLessThanOrEqual(1024);expect(data.text).not.toContain('�');}else {expect(data.text).toBeUndefined();expect(data.errorCode).toBe('CLOUD_MODEL_RESPONSE_REJECTED');}expect(await rpc(name!,'audit')).toEqual({leak:false});}});
  it('preserves the current repair alarm generation while queued maintenance changes',async()=>{await enqueue('fence','one',{availableAt:now+1000});const original=await rpc('fence','alarm');const result=await rpc<{alarm:number}>('fence','scheduling',{busy:true,retrying:true});expect(result.alarm).toBe(original);await enqueue('fence','two',{availableAt:now+500});expect(await rpc('fence','alarm')).toBe(original);await rpc('fence','scheduling',{busy:false,retrying:false});expect(await rpc('fence','alarm')).toBe(now+500);});
});

describe('frozen inbox schema',()=>{it('rejects accessors without invoking them',()=>{let called=0;const value=Object.defineProperty({dedupKey:'one',source:'message'},'text',{enumerable:true,get(){called++;return 'text';}});expect(()=>admitCloudInbox(value)).toThrow('CLOUD_REQUEST_INVALID');expect(called).toBe(0);});});
